debuging

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -113,21 +113,21 @@ jobs:
               --file-exists-behavior OVERWRITE \
               --description "Development env backend deployment - $BUILD_NUMBER" --region ${{ secrets.AWS_REGION }} | jq -r '.deploymentId')
           deploymentStatus="" 
-          while : ; do
-            status=$(aws deploy get-deployment --deployment-id $deploymentId --region ${{ secrets.AWS_REGION }} | jq -r '.deploymentInfo.status')
-
-            if [ "$status" != "Created" ] && [ "$status" != "InProgress" ] && [ "$status" != "Pending" ]; then
-              if [ "$status" == "Succeeded" ]; then
-                echo "Deployment Successful"
-                export deploymentStatus=0
-                break
-              else
-                export deploymentStatus=1
-                echo "Deployment failed. Check the AWS Codedeploy for more information"
-                break
-              fi
-            fi
-
-            sleep 10
-          done
-          exit $deploymentStatus
+#          while : ; do
+#            status=$(aws deploy get-deployment --deployment-id $deploymentId --region ${{ secrets.AWS_REGION }} | jq -r '.deploymentInfo.status')
+#
+#            if [ "$status" != "Created" ] && [ "$status" != "InProgress" ] && [ "$status" != "Pending" ]; then
+#              if [ "$status" == "Succeeded" ]; then
+#                echo "Deployment Successful"
+#                export deploymentStatus=0
+#                break
+#              else
+#                export deploymentStatus=1
+#                echo "Deployment failed. Check the AWS Codedeploy for more information"
+#                break
+#              fi
+#            fi
+#
+#            sleep 10
+#          done
+#          exit $deploymentStatus
